# current configuration for indexing in the retrieval system without experimentation
# "_cur": suffix for current configuration 
embedding_model_cur: all-mpnet-base-v2
index_name_cur: epilepsy-chatbot
metric_cur: cosine
chunk_size_cur: 700
region_cur: us-east-1
